#pragma once

// #define MASTER_LEFT

#undef RGBLED_NUM
#define RGBLIGHT_ANIMATIONS
#define RGBLED_NUM 12
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8

#define NO_DEBUG
#define NO_PRINT
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

// #define RAW_EABLE

